# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/hectobyte1024/Documents/sdl shader compiler"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/hectobyte1024/Documents/sdl shader compiler/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" "/home/hectobyte1024/Documents/sdl shader compiler/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdl_compiler_lib

# Build rule for target.
sdl_compiler_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_compiler_lib
.PHONY : sdl_compiler_lib

# fast build rule for target.
sdl_compiler_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/build
.PHONY : sdl_compiler_lib/fast

#=============================================================================
# Target rules for targets named sdl_compiler

# Build rule for target.
sdl_compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_compiler
.PHONY : sdl_compiler

# fast build rule for target.
sdl_compiler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler.dir/build.make CMakeFiles/sdl_compiler.dir/build
.PHONY : sdl_compiler/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named release

# Build rule for target.
release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 release
.PHONY : release

# fast build rule for target.
release/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/release.dir/build.make CMakeFiles/release.dir/build
.PHONY : release/fast

src/cli/cli_parser.o: src/cli/cli_parser.cpp.o
.PHONY : src/cli/cli_parser.o

# target to build an object file
src/cli/cli_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler.dir/build.make CMakeFiles/sdl_compiler.dir/src/cli/cli_parser.cpp.o
.PHONY : src/cli/cli_parser.cpp.o

src/cli/cli_parser.i: src/cli/cli_parser.cpp.i
.PHONY : src/cli/cli_parser.i

# target to preprocess a source file
src/cli/cli_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler.dir/build.make CMakeFiles/sdl_compiler.dir/src/cli/cli_parser.cpp.i
.PHONY : src/cli/cli_parser.cpp.i

src/cli/cli_parser.s: src/cli/cli_parser.cpp.s
.PHONY : src/cli/cli_parser.s

# target to generate assembly for a file
src/cli/cli_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler.dir/build.make CMakeFiles/sdl_compiler.dir/src/cli/cli_parser.cpp.s
.PHONY : src/cli/cli_parser.cpp.s

src/codegen/base_generator.o: src/codegen/base_generator.cpp.o
.PHONY : src/codegen/base_generator.o

# target to build an object file
src/codegen/base_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o
.PHONY : src/codegen/base_generator.cpp.o

src/codegen/base_generator.i: src/codegen/base_generator.cpp.i
.PHONY : src/codegen/base_generator.i

# target to preprocess a source file
src/codegen/base_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.i
.PHONY : src/codegen/base_generator.cpp.i

src/codegen/base_generator.s: src/codegen/base_generator.cpp.s
.PHONY : src/codegen/base_generator.s

# target to generate assembly for a file
src/codegen/base_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.s
.PHONY : src/codegen/base_generator.cpp.s

src/codegen/cuda_generator.o: src/codegen/cuda_generator.cpp.o
.PHONY : src/codegen/cuda_generator.o

# target to build an object file
src/codegen/cuda_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o
.PHONY : src/codegen/cuda_generator.cpp.o

src/codegen/cuda_generator.i: src/codegen/cuda_generator.cpp.i
.PHONY : src/codegen/cuda_generator.i

# target to preprocess a source file
src/codegen/cuda_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.i
.PHONY : src/codegen/cuda_generator.cpp.i

src/codegen/cuda_generator.s: src/codegen/cuda_generator.cpp.s
.PHONY : src/codegen/cuda_generator.s

# target to generate assembly for a file
src/codegen/cuda_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.s
.PHONY : src/codegen/cuda_generator.cpp.s

src/codegen/glsl_generator.o: src/codegen/glsl_generator.cpp.o
.PHONY : src/codegen/glsl_generator.o

# target to build an object file
src/codegen/glsl_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o
.PHONY : src/codegen/glsl_generator.cpp.o

src/codegen/glsl_generator.i: src/codegen/glsl_generator.cpp.i
.PHONY : src/codegen/glsl_generator.i

# target to preprocess a source file
src/codegen/glsl_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.i
.PHONY : src/codegen/glsl_generator.cpp.i

src/codegen/glsl_generator.s: src/codegen/glsl_generator.cpp.s
.PHONY : src/codegen/glsl_generator.s

# target to generate assembly for a file
src/codegen/glsl_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.s
.PHONY : src/codegen/glsl_generator.cpp.s

src/compiler/compiler.o: src/compiler/compiler.cpp.o
.PHONY : src/compiler/compiler.o

# target to build an object file
src/compiler/compiler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o
.PHONY : src/compiler/compiler.cpp.o

src/compiler/compiler.i: src/compiler/compiler.cpp.i
.PHONY : src/compiler/compiler.i

# target to preprocess a source file
src/compiler/compiler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.i
.PHONY : src/compiler/compiler.cpp.i

src/compiler/compiler.s: src/compiler/compiler.cpp.s
.PHONY : src/compiler/compiler.s

# target to generate assembly for a file
src/compiler/compiler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.s
.PHONY : src/compiler/compiler.cpp.s

src/lexer/lexer.o: src/lexer/lexer.cpp.o
.PHONY : src/lexer/lexer.o

# target to build an object file
src/lexer/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o
.PHONY : src/lexer/lexer.cpp.o

src/lexer/lexer.i: src/lexer/lexer.cpp.i
.PHONY : src/lexer/lexer.i

# target to preprocess a source file
src/lexer/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.i
.PHONY : src/lexer/lexer.cpp.i

src/lexer/lexer.s: src/lexer/lexer.cpp.s
.PHONY : src/lexer/lexer.s

# target to generate assembly for a file
src/lexer/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.s
.PHONY : src/lexer/lexer.cpp.s

src/lexer/token.o: src/lexer/token.cpp.o
.PHONY : src/lexer/token.o

# target to build an object file
src/lexer/token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o
.PHONY : src/lexer/token.cpp.o

src/lexer/token.i: src/lexer/token.cpp.i
.PHONY : src/lexer/token.i

# target to preprocess a source file
src/lexer/token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.i
.PHONY : src/lexer/token.cpp.i

src/lexer/token.s: src/lexer/token.cpp.s
.PHONY : src/lexer/token.s

# target to generate assembly for a file
src/lexer/token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.s
.PHONY : src/lexer/token.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler.dir/build.make CMakeFiles/sdl_compiler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler.dir/build.make CMakeFiles/sdl_compiler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler.dir/build.make CMakeFiles/sdl_compiler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser/ast.o: src/parser/ast.cpp.o
.PHONY : src/parser/ast.o

# target to build an object file
src/parser/ast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o
.PHONY : src/parser/ast.cpp.o

src/parser/ast.i: src/parser/ast.cpp.i
.PHONY : src/parser/ast.i

# target to preprocess a source file
src/parser/ast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.i
.PHONY : src/parser/ast.cpp.i

src/parser/ast.s: src/parser/ast.cpp.s
.PHONY : src/parser/ast.s

# target to generate assembly for a file
src/parser/ast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.s
.PHONY : src/parser/ast.cpp.s

src/parser/parser.o: src/parser/parser.cpp.o
.PHONY : src/parser/parser.o

# target to build an object file
src/parser/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o
.PHONY : src/parser/parser.cpp.o

src/parser/parser.i: src/parser/parser.cpp.i
.PHONY : src/parser/parser.i

# target to preprocess a source file
src/parser/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.i
.PHONY : src/parser/parser.cpp.i

src/parser/parser.s: src/parser/parser.cpp.s
.PHONY : src/parser/parser.s

# target to generate assembly for a file
src/parser/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.s
.PHONY : src/parser/parser.cpp.s

src/semantic/analyzer.o: src/semantic/analyzer.cpp.o
.PHONY : src/semantic/analyzer.o

# target to build an object file
src/semantic/analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o
.PHONY : src/semantic/analyzer.cpp.o

src/semantic/analyzer.i: src/semantic/analyzer.cpp.i
.PHONY : src/semantic/analyzer.i

# target to preprocess a source file
src/semantic/analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.i
.PHONY : src/semantic/analyzer.cpp.i

src/semantic/analyzer.s: src/semantic/analyzer.cpp.s
.PHONY : src/semantic/analyzer.s

# target to generate assembly for a file
src/semantic/analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.s
.PHONY : src/semantic/analyzer.cpp.s

src/semantic/symbol_table.o: src/semantic/symbol_table.cpp.o
.PHONY : src/semantic/symbol_table.o

# target to build an object file
src/semantic/symbol_table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o
.PHONY : src/semantic/symbol_table.cpp.o

src/semantic/symbol_table.i: src/semantic/symbol_table.cpp.i
.PHONY : src/semantic/symbol_table.i

# target to preprocess a source file
src/semantic/symbol_table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.i
.PHONY : src/semantic/symbol_table.cpp.i

src/semantic/symbol_table.s: src/semantic/symbol_table.cpp.s
.PHONY : src/semantic/symbol_table.s

# target to generate assembly for a file
src/semantic/symbol_table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.s
.PHONY : src/semantic/symbol_table.cpp.s

src/utils/error_handler.o: src/utils/error_handler.cpp.o
.PHONY : src/utils/error_handler.o

# target to build an object file
src/utils/error_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o
.PHONY : src/utils/error_handler.cpp.o

src/utils/error_handler.i: src/utils/error_handler.cpp.i
.PHONY : src/utils/error_handler.i

# target to preprocess a source file
src/utils/error_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.i
.PHONY : src/utils/error_handler.cpp.i

src/utils/error_handler.s: src/utils/error_handler.cpp.s
.PHONY : src/utils/error_handler.s

# target to generate assembly for a file
src/utils/error_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.s
.PHONY : src/utils/error_handler.cpp.s

src/utils/file_utils.o: src/utils/file_utils.cpp.o
.PHONY : src/utils/file_utils.o

# target to build an object file
src/utils/file_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o
.PHONY : src/utils/file_utils.cpp.o

src/utils/file_utils.i: src/utils/file_utils.cpp.i
.PHONY : src/utils/file_utils.i

# target to preprocess a source file
src/utils/file_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.i
.PHONY : src/utils/file_utils.cpp.i

src/utils/file_utils.s: src/utils/file_utils.cpp.s
.PHONY : src/utils/file_utils.s

# target to generate assembly for a file
src/utils/file_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sdl_compiler_lib.dir/build.make CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.s
.PHONY : src/utils/file_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... debug"
	@echo "... release"
	@echo "... sdl_compiler"
	@echo "... sdl_compiler_lib"
	@echo "... src/cli/cli_parser.o"
	@echo "... src/cli/cli_parser.i"
	@echo "... src/cli/cli_parser.s"
	@echo "... src/codegen/base_generator.o"
	@echo "... src/codegen/base_generator.i"
	@echo "... src/codegen/base_generator.s"
	@echo "... src/codegen/cuda_generator.o"
	@echo "... src/codegen/cuda_generator.i"
	@echo "... src/codegen/cuda_generator.s"
	@echo "... src/codegen/glsl_generator.o"
	@echo "... src/codegen/glsl_generator.i"
	@echo "... src/codegen/glsl_generator.s"
	@echo "... src/compiler/compiler.o"
	@echo "... src/compiler/compiler.i"
	@echo "... src/compiler/compiler.s"
	@echo "... src/lexer/lexer.o"
	@echo "... src/lexer/lexer.i"
	@echo "... src/lexer/lexer.s"
	@echo "... src/lexer/token.o"
	@echo "... src/lexer/token.i"
	@echo "... src/lexer/token.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser/ast.o"
	@echo "... src/parser/ast.i"
	@echo "... src/parser/ast.s"
	@echo "... src/parser/parser.o"
	@echo "... src/parser/parser.i"
	@echo "... src/parser/parser.s"
	@echo "... src/semantic/analyzer.o"
	@echo "... src/semantic/analyzer.i"
	@echo "... src/semantic/analyzer.s"
	@echo "... src/semantic/symbol_table.o"
	@echo "... src/semantic/symbol_table.i"
	@echo "... src/semantic/symbol_table.s"
	@echo "... src/utils/error_handler.o"
	@echo "... src/utils/error_handler.i"
	@echo "... src/utils/error_handler.s"
	@echo "... src/utils/file_utils.o"
	@echo "... src/utils/file_utils.i"
	@echo "... src/utils/file_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

