# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/hectobyte1024/Documents/sdl shader compiler"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/hectobyte1024/Documents/sdl shader compiler/build"

# Include any dependencies generated for this target.
include CMakeFiles/sdl_compiler_lib.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/sdl_compiler_lib.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/sdl_compiler_lib.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/sdl_compiler_lib.dir/flags.make

CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/lexer/lexer.cpp
CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/lexer/lexer.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/lexer/lexer.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/lexer/lexer.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/lexer/token.cpp
CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/lexer/token.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/lexer/token.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/lexer/token.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/parser/parser.cpp
CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/parser/parser.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/parser/parser.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/parser/parser.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/parser/ast.cpp
CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/parser/ast.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/parser/ast.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/parser/ast.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/semantic/analyzer.cpp
CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/semantic/analyzer.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/semantic/analyzer.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/semantic/analyzer.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/semantic/symbol_table.cpp
CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/semantic/symbol_table.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/semantic/symbol_table.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/semantic/symbol_table.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/codegen/glsl_generator.cpp
CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/glsl_generator.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/glsl_generator.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/glsl_generator.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/codegen/cuda_generator.cpp
CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_8) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/cuda_generator.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/cuda_generator.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/cuda_generator.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/codegen/base_generator.cpp
CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_9) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/base_generator.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/base_generator.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/codegen/base_generator.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/compiler/compiler.cpp
CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_10) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/compiler/compiler.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/compiler/compiler.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/compiler/compiler.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/utils/error_handler.cpp
CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_11) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/utils/error_handler.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/utils/error_handler.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/utils/error_handler.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.s

CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o: CMakeFiles/sdl_compiler_lib.dir/flags.make
CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o: /home/hectobyte1024/Documents/sdl\ shader\ compiler/src/utils/file_utils.cpp
CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o: CMakeFiles/sdl_compiler_lib.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_12) "Building CXX object CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o -MF CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o.d -o CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o -c "/home/hectobyte1024/Documents/sdl shader compiler/src/utils/file_utils.cpp"

CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/hectobyte1024/Documents/sdl shader compiler/src/utils/file_utils.cpp" > CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.i

CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/hectobyte1024/Documents/sdl shader compiler/src/utils/file_utils.cpp" -o CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.s

# Object files for target sdl_compiler_lib
sdl_compiler_lib_OBJECTS = \
"CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o" \
"CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o"

# External object files for target sdl_compiler_lib
sdl_compiler_lib_EXTERNAL_OBJECTS =

libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/lexer/lexer.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/lexer/token.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/parser/parser.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/parser/ast.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/semantic/analyzer.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/semantic/symbol_table.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/codegen/glsl_generator.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/codegen/cuda_generator.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/codegen/base_generator.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/compiler/compiler.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/utils/error_handler.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/src/utils/file_utils.cpp.o
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/build.make
libsdl_compiler_lib.a: CMakeFiles/sdl_compiler_lib.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir="/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_13) "Linking CXX static library libsdl_compiler_lib.a"
	$(CMAKE_COMMAND) -P CMakeFiles/sdl_compiler_lib.dir/cmake_clean_target.cmake
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/sdl_compiler_lib.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/sdl_compiler_lib.dir/build: libsdl_compiler_lib.a
.PHONY : CMakeFiles/sdl_compiler_lib.dir/build

CMakeFiles/sdl_compiler_lib.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/sdl_compiler_lib.dir/cmake_clean.cmake
.PHONY : CMakeFiles/sdl_compiler_lib.dir/clean

CMakeFiles/sdl_compiler_lib.dir/depend:
	cd "/home/hectobyte1024/Documents/sdl shader compiler/build" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/home/hectobyte1024/Documents/sdl shader compiler" "/home/hectobyte1024/Documents/sdl shader compiler" "/home/hectobyte1024/Documents/sdl shader compiler/build" "/home/hectobyte1024/Documents/sdl shader compiler/build" "/home/hectobyte1024/Documents/sdl shader compiler/build/CMakeFiles/sdl_compiler_lib.dir/DependInfo.cmake" --color=$(COLOR)
.PHONY : CMakeFiles/sdl_compiler_lib.dir/depend

