# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# compile CXX with /usr/bin/c++
CXX_DEFINES = 

CXX_INCLUDES = -I"/home/hectobyte1024/Documents/sdl shader compiler/include" -I"/home/hectobyte1024/Documents/sdl shader compiler/src"

CXX_FLAGS = -O3 -DNDEBUG -Wall -Wextra -Wpedantic -std=gnu++17

